# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel, Field
from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class Company(BaseModel):
    """
    Company entity.

    Identifiers: 1
    Relationships: 1
    """
    # primary identifier
    id_: int
    name: str
    tax_id: Optional[str] = None
    persons: List[Person] = None

    def get_id(self) -> str:
        """Get the primary identifier."""
        return self.id

    async def load_persons(self) -> List['Person']:
        """Load related Person entities."""
        # TODO: Implement lazy loading
        return []

    model_config = {
        "validate_assignment": True,
        "arbitrary_types_allowed": True,
    }