# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel, Field
from typing import List, Optional, TYPE_CHECKING
from ..enums.nationality import Nationality

if TYPE_CHECKING:
    from .company import Company

class Person(BaseModel):
    """
    Person entity.

    Identifiers: 1
    Relationships: 1
    """
    email: str
    # primary identifier
    id_: int
    last_name: str
    nationality: Nationality
    company_id: Optional[str] = None
    company: Company

    def get_id(self) -> str:
        """Get the primary identifier."""
        return self.id

    async def load_company(self) -> Optional['Company']:
        """Load related Company entity."""
        # TODO: Implement lazy loading
        return None

    model_config = {
        "validate_assignment": True,
        "arbitrary_types_allowed": True,
    }