# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class Company(BaseModel):
    """Company model."""
    id_: int
    name: str
    tax_id: Optional[str] = None
    person: Optional[List[Person]] = None