# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class ContactInfo(BaseModel):
    """ContactInfo model."""
    email: str
    id_: int
    person_id: Optional[str] = None
    person: Optional['Person'] = None