# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import Optional, TYPE_CHECKING
from ..enums.nationality import Nationality

if TYPE_CHECKING:
    from .company import Company
    from .contact_info import ContactInfo

class Person(BaseModel):
    """Person model."""
    first_name: str
    id_: int
    last_name: str
    nationality: Nationality
    company_id: Optional[str] = None
    company: Optional['Company'] = None
    contact_info: Optional['ContactInfo'] = None

    model_config = {
        "validate_assignment": True,
        "use_enum_values": True,
    }