# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel, Field
from typing import Optional


class Address(BaseModel):
    """Address data transfer object."""
    city: str
    house_nr: str
    street: str
    zip_code: str